### ISSUE TITLE
Add some space before team name and border of table

### ISSUE THREAD

**Issue by jportella93** [jportella93/make-me-drink-client#12]
In the screenshot, "jon jake" is too close to the start of the table. Add some space between the table left border and the name of the team.

![Screenshot 2020-10-08 at 11 02 57](https://user-images.githubusercontent.com/35599326/95437939-f0196b80-0955-11eb-87b9-05487d0f6d8b.png)

**Comment by ahmad-reza619** [comment]
can i take this on @jportella93 ?

**Comment by jportella93** [comment]
For sure :)

**Comment by MuhammadTanveer94** [comment]
I want to do this? @jportella93

**Comment by jportella93** [comment]
@MuhammadTanveer94 sure!
