### ISSUE TITLE
Make more obvious that the lightbulb is to suggest a question

### ISSUE THREAD

**Issue by jportella93** [jportella93/make-me-drink-client#7]
Maybe make it blink after some seconds?

To test it, run it with the back-end https://github.com/jportella93/make-me-drink-server

**Comment by prakashait9** [comment]
@jportella93 you want bulb to glow or that whole button to glow ?

**Comment by jportella93** [comment]
@prakashait9 whatever you feel like looks better :)

**Comment by prakashait9** [comment]
cool, I will work on this one then

**Comment by prakashait9** [comment]
@jportella93  Does [this](https://gifyu.com/image/6j1z) look fine to you ?

**Comment by jportella93** [comment]
Really nice! 😄

**Comment by prakashait9** [comment]
hey @jportella93  sorry, the css class I gave is getting overridden in button
need to figure out why
I was about to close PR, but you were faster than me

**Comment by jportella93** [comment]
Oh okay, then feel free to merge it after fixing it :)

**Comment by prakashait9** [comment]
Fixed in this [PR](https://github.com/jportella93/make-me-drink-client/pull/10) 🙂

**Comment by prakashait9** [comment]
Hi @jportella93 
I got this message - 
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR. 

Please can you check.

**Comment by jportella93** [comment]
@prakashait9 I've added the hacktoberfest-accepted label to the PR, is that working now?

**Comment by prakashait9** [comment]
Yes, thanks 😃
